- name: system base configure
  hosts: localhost
  vars:
    host_name: testing
    packages_extension:
      - gcc
    base_selinux_disabled: true
    base_nameserver_servers:
      - 114.114.114.114
  roles:
    - ansible-role-base
